### ISSUE TITLE
can not find game ?

### ISSUE THREAD

**Issue by holicc** [toxa9/CSGOInjector#6]
follow steps:
1.download from github.
2.run csgo with steam.
3.run injector.
4.selected Osiris dll.
5.message box show can not find the game.

**Comment by toxa9** [comment]
I'll check it out in my free time.

**Comment by deltaheiwa** [comment]
Still not fixed :(

**Comment by toxa9** [comment]
Hi @holicc @blushydan the problem has been fixed, tested with [Osiris](https://github.com/danielkrupinski/Osiris) everything seems to work ok.
U can download new version from [Releases](https://github.com/toxa9/CSGOInjector/releases/tag/1.3) or download and compile new version of project.
